AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'BAB AI Backend API - Production Ready'

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production
        DB_HOST: !Ref DbHost
        DB_PORT: !Ref DbPort
        DB_DATABASE: !Ref DbDatabase
        DB_USER: !Ref DbUser
        DB_PASSWORD: !Ref DbPassword
        DB_SSL: !Ref DbSsl
        FRONTEND_URL: !Ref FrontendUrl
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Requested-With'"
      AllowOrigin: "'*'"

Parameters:
  Stage:
    Type: String
    Default: prod
    Description: API Gateway stage name
  DbHost:
    Type: String
    Description: Database host endpoint (e.g., your-rds.region.rds.amazonaws.com)
  DbPort:
    Type: String
    Default: '5432'
    Description: Database port
  DbDatabase:
    Type: String
    Default: babai_production
    Description: Database name
  DbUser:
    Type: String
    Default: babai_admin
    Description: Database username
  DbPassword:
    Type: String
    NoEcho: true
    Description: Database password (secure)
  DbSsl:
    Type: String
    Default: 'true'
    Description: Enable SSL for database connection
  FrontendUrl:
    Type: String
    Default: 'https://main.d3u6tp5amhwi3s.amplifyapp.com'
    Description: Frontend URL for CORS

Resources:
  BabAiApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'babai-backend-${Stage}'
      CodeUri: ./
      Handler: src/index.handler
      Description: 'BAB AI Backend API Lambda Function'
      Events:
        ApiProxyAny:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRootAny:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: production

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL for BAB AI Backend'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  FunctionName:
    Description: 'Lambda function name'
    Value: !Ref BabAiApi
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'
